apiVersion: v1
kind: ResourceQuota
metadata:
  name: notes-app-quota
  namespace: notes-app
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
